version: "3.8"

services:
  backend:
    build: .
    container_name: mbus-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      INDOOR_MONGO_URI: mongodb://172.31.96.1:27017
      REDIS_URL: redis://host.docker.internal:6379
    volumes:
      - .:/app
      - /app/node_modules
    command: npx tsx src/app.ts